version: "3"
services:
  go:
    build:
      context: .
      dockerfile: go.Dockerfile
    labels:
      - "traefik.http.routers.go.rule=Host(`api.tangzhenming.com`)"
      - "traefik.http.services.go.loadbalancer.server.port=80"
    container_name: go

networks:
  default:
    external:
      name: my_traefik_default
