version: "3"
services:
  go:
    build:
      context: .
      dockerfile: go.Dockerfile
    env_file:
      - .env # 指定 env 文件
    labels:
      - "traefik.http.routers.go.rule=Host(`api.tangzhenming.com`)"
    container_name: go

networks:
  default:
    external:
      name: my_traefik_default
