host: localhost:8080
info:
  contact:
    email: tangzhenming1207@gmail.com
    name: Ryan
  description: API GO 接口文档
  title: API GO
  version: "1.0"
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Create a user
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Update a user
    get:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Read a user
    put:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Update a user
swagger: "2.0"
